languageCode = "en-us"
title = "CASTogether"
baseURL = "http://www.castogether.com"
theme = "hugo-theme-dopetrope"
publishDir = "docs"

[params.event]
    title = "Events"
    foldername = "events"
    findoutmoretext = "Find out more"

[[menu.main]]
    name = "Past Events"
    weight = 200
    url = "/events"
[[menu.main]]
    name = "About CAST"
    weight = 100
    url = "/about"
[[menu.main]]
    name = "Upcoming"
    weight = 150
    url = "/events/cast6"
